### ISSUE TITLE
Bus Edition

### ISSUE THREAD

**Issue by loren138** [jakswa/martaionic#5]
Hi,

I've very much enjoyed using marta.io.  Two questions for you.

1. Do you have a license that you are releasing code under?
2. Do you have any interest in a bus edition or section of your app?  I've developed a semi-similar setup using the bus API.  The downside is the bus API shows time early/last by route not time until arrival by stop which may be confusing for people since that is different than what this API does.  If the GTFS files are up-to-date, the time until a stop can be computed, but that's more intensive.

My current result is here: http://klingman.us/bus?id=120  You can view any route by placing the route id in the url.  As you can see, I've used your timebox CSS, which is why I was curious about the license.  (If you wanted bus to be a separate app which I developed, I'd be interested in using all of the current source code.)

Note: This is currently meant for use by a few select people so I know it would need some cleaning up to be generally useful.

**Comment by jakswa** [comment]
1. Oh man, thanks for bringing licensing up. I addressed that in #6. It's MIT license, so feel free to reuse any of this.
2. It's been so long since I've given this project any love that I welcome any contributions. If you add a bus view, I'll do my best to get it merged and released to the appstore apps. It's kind of open season on this repo. I have a sinking feeling that all the deployment processes for this app are a broken mess, since it's sat for a long time. Maybe luck is with us and it'll be a breeze.
    - All my attempts to get a similar view for buses went kind of messy, maybe because I don't ride buses enough. You need to know ID or route name, and then need to know which bus to put at the top? And I remember not being sure which bus is most relevant? That was a long time ago, maybe it's changed.
    - When I've talked about buses to other people, there have been requests for non-marta bus routes to be included (CCT, for example). Marta has a monopoly on trains, it seems, but people take other bus services. It's not a requirement or anything. I'm more preparing us for the requests we'll see, if we only add Marta.

In other news, I did recently read that [ionic 2 final is out](http://blog.ionic.io/announcing-ionic-2-0-0-final/), and I'm kind of itching to write something in it, to check it out. So, if you're looking for a lot more to chew off, I'm on board for working on that. :)

**Comment by loren138** [comment]
> All my attempts to get a similar view for buses went kind of messy, maybe because I don't ride buses enough. You need to know ID or route name, and then need to know which bus to put at the top? And I remember not being sure which bus is most relevant? That was a long time ago, maybe it's changed.

Yes to all of these, my approach just shows all the buses sorted by direction of travel and you have to decide which bus is relevant and do your own math to figure out when it will arrive at your stop so it's not clean, but it doesn't crash if marta fails to update their GTFS file (which contains the information needed to make better presentation).  OneBusAway does display the info (using GTFS), just not in nearly as clean of a format and it crashes if Marta fails to get the new GTFS file out.  It would probably be better to contribute to OneBusAway rather than develop a complete GTFS solution for Marta.

Do you have any plans to go to the next Marta Hackathon? https://www.eventbrite.com/e/marta-hackathon-smart-city-iot-tickets-28164963163?aff=erelexpmlt

**Comment by jakswa** [comment]
> Do you have any plans to go to the next Marta Hackathon?

~~Yes!~~ No, this upcoming one conflicts with travel plans I have 😭. I [attended](https://twitter.com/jakswa/status/792491475863035904) the last one, and even had [some ideas](https://github.com/jakswa/martaionic/wiki/MARTA-Hackathon-Ideas) for things to work on (which I didn't end up proposing, and ended up helping out on a Phoenix project). You can find me idling in the [code for atlanta slack](http://slack.codeforatlanta.org/), which we used to organize teams at the last hackathon.

**Comment by christian-blades-cb** [comment]
@jakswa Psst, might want to fill in the blanks on that LICENSE.

**Comment by jakswa** [comment]
done, thanks!

![img](https://media.giphy.com/media/jL6OeIhk3zPi/giphy.gif)
